const TERM_DEAL_IDS = new Set([
  'venture',
  'equity',
  'short_term_sublet',
  'mortgage_refi',
  'taxi_lease',
  'municipal_bond_pool',
  'dividend_note',
  'structured_note',
  'p2p_loans',
  'invoice_factoring',
  'equipment_leasing',
  'fintech_microloan',
  'franchise_buyback',
]);

const RAW_DEAL_TEMPLATES = [
  {
    id: 'venture',
    title: 'Конвертируемый займ в SaaS',
    description: 'Микро‑раунд с правом конвертации долга в долю.',
    icon: 'iconGrowth',
    entryCost: 2400,
    monthlyPayout: 160,
    durationMonths: 9,
    riskNote: 'Высокий риск — при провале возможна потеря взноса.',
    features: ['Вход: $2 400', 'Пассивно: +$160/мес.', 'Опция конвертации через 9 мес.'],
    riskMeter: 5,
    liquidityMeter: 1,
    lockMonths: 9,
    effects: [
      { icon: '⚡', text: 'Риск потери взноса' },
      { icon: '📈', text: 'Потенциал роста при конвертации' },
      { icon: '💰', text: '+$160/мес.' },
    ],
    window: { minTurns: 3, maxTurns: 5, slots: 1 },
  },
  {
    id: 'equity',
    title: 'Доля в стоматологическом кабинете',
    description: 'Часть прибыли с фиксированным обратным выкупом.',
    icon: 'iconCard',
    entryCost: 2600,
    monthlyPayout: 170,
    durationMonths: 14,
    riskNote: 'Средний риск — возможна задержка выплат до 1-2 мес.',
    features: ['Вход: $2 600', 'Дивиденд: +$170/мес.', 'Выкуп по $5 100 через 14 мес.'],
    riskMeter: 3,
    liquidityMeter: 3,
    lockMonths: 14,
    effects: [
      { icon: '🧱', text: 'Фикс. выкуп по договору' },
      { icon: '💰', text: '+$170/мес.' },
      { icon: '⚡', text: 'Задержки возможны' },
    ],
    window: { minTurns: 3, maxTurns: 6, slots: 2 },
  },
  {
    id: 'real_estate',
    title: 'Студия в пригороде',
    description: 'Взнос в объект под долгосрочную аренду.',
    icon: 'iconHardhat',
    entryCost: 2800,
    monthlyPayout: 190,
    durationMonths: 16,
    riskNote: 'Низкий риск — стабильная аренда, но деньги заморожены.',
    features: ['Вход: $2 800', 'Кеш-флоу: +$190/мес.', 'Опция выкупа управляющим'],
    riskMeter: 2,
    liquidityMeter: 1,
    lockMonths: 16,
    effects: [
      { icon: '💰', text: '+$190/мес.' },
      { icon: '🧱', text: 'Содержание: $90/мес.' },
      { icon: '⚡', text: 'Долгая заморозка' },
    ],
    window: { minTurns: 3, maxTurns: 6, slots: 2 },
  },
  {
    id: 'auto',
    title: 'Флот каршеринга',
    description: 'Доля в выручке городского каршеринга.',
    icon: 'iconPiggy',
    entryCost: 2200,
    monthlyPayout: 150,
    durationMonths: 9,
    riskNote: 'Средний риск — зависит от загрузки и сезона.',
    features: ['Вход: $2 200', 'Выручка: +$150/мес.', 'Срок: 9 мес.'],
    riskMeter: 3,
    liquidityMeter: 3,
    lockMonths: 9,
    effects: [
      { icon: '💰', text: '+$150/мес.' },
      { icon: '🚗', text: 'Загрузка автопарка' },
      { icon: '⚡', text: 'Сезонные колебания' },
    ],
    window: { minTurns: 2, maxTurns: 4, slots: 2 },
  },
  {
    id: 'rent_renovation',
    title: 'Ремонт под аренду',
    description: 'Мелкий ремонт квартиры и сдача долгосрочно.',
    icon: 'iconHardhat',
    entryCost: 3500,
    monthlyPayout: 190,
    durationMonths: 14,
    riskNote: 'Низкий риск — зависит от заполняемости.',
    features: ['Вход: $3 500', 'Аренда: +$190/мес.', 'Срок: 14 мес.'],
    riskMeter: 2,
    liquidityMeter: 2,
    lockMonths: 14,
    effects: [
      { icon: '💰', text: '+$190/мес.' },
      { icon: '🏠', text: 'Стабильная аренда' },
      { icon: '⚡', text: 'Риск простоя 1-2 мес.' },
    ],
    window: { minTurns: 3, maxTurns: 6, slots: 2 },
  },
  {
    id: 'co_living_room',
    title: 'Комната в ко‑ливинге',
    description: 'Место в ко‑ливинге с краткосрочной арендой.',
    icon: 'iconSmile',
    entryCost: 1200,
    monthlyPayout: 90,
    durationMonths: 10,
    riskNote: 'Средний риск — сезонность спроса.',
    features: ['Вход: $1 200', 'Аренда: +$90/мес.', 'Срок: 10 мес.'],
    riskMeter: 3,
    liquidityMeter: 3,
    lockMonths: 10,
    effects: [
      { icon: '💰', text: '+$90/мес.' },
      { icon: '📅', text: 'Сезонный спрос' },
      { icon: '⚡', text: 'Возможны паузы' },
    ],
    window: { minTurns: 2, maxTurns: 5, slots: 3 },
  },
  {
    id: 'parking_spot',
    title: 'Паркинг у делового центра',
    description: 'Доля в паркинге с фиксированным арендным потоком.',
    icon: 'iconCard',
    entryCost: 1800,
    monthlyPayout: 110,
    durationMonths: 12,
    riskNote: 'Низкий риск — долгосрочные контракты.',
    features: ['Вход: $1 800', 'Аренда: +$110/мес.', 'Срок: 12 мес.'],
    riskMeter: 2,
    liquidityMeter: 3,
    lockMonths: 12,
    effects: [
      { icon: '💰', text: '+$110/мес.' },
      { icon: '🧱', text: 'Фикс. договора' },
      { icon: '⚡', text: 'Редкие простои' },
    ],
    window: { minTurns: 2, maxTurns: 4, slots: 2 },
  },
  {
    id: 'storage_unit',
    title: 'Складской бокс',
    description: 'Небольшой бокс под хранение для бизнеса и частных лиц.',
    icon: 'iconCart',
    entryCost: 1500,
    monthlyPayout: 95,
    durationMonths: 9,
    riskNote: 'Низкий риск — краткосрочные договоры.',
    features: ['Вход: $1 500', 'Аренда: +$95/мес.', 'Срок: 9 мес.'],
    riskMeter: 2,
    liquidityMeter: 4,
    lockMonths: 9,
    effects: [
      { icon: '💰', text: '+$95/мес.' },
      { icon: '📦', text: 'Стабильный спрос' },
      { icon: '⚡', text: 'Возможна ротация клиентов' },
    ],
    window: { minTurns: 1, maxTurns: 3, slots: 3 },
  },
  {
    id: 'suburban_cottage',
    title: 'Коттедж на выходные',
    description: 'Краткосрочная аренда коттеджа по выходным.',
    icon: 'iconPlant',
    entryCost: 4200,
    monthlyPayout: 220,
    durationMonths: 12,
    riskNote: 'Средний риск — сильная сезонность.',
    features: ['Вход: $4 200', 'Аренда: +$220/мес.', 'Срок: 12 мес.'],
    riskMeter: 3,
    liquidityMeter: 2,
    lockMonths: 12,
    effects: [
      { icon: '💰', text: '+$220/мес.' },
      { icon: '🌦️', text: 'Сезонные пики' },
      { icon: '⚡', text: 'Риск простоя зимой' },
    ],
    window: { minTurns: 3, maxTurns: 6, slots: 2 },
  },
  {
    id: 'short_term_sublet',
    title: 'Субаренда у вокзала',
    description: 'Сдача квартиры на короткий срок с высокой ротацией.',
    icon: 'iconCoins',
    entryCost: 2600,
    monthlyPayout: 210,
    durationMonths: 8,
    riskNote: 'Средний риск — нужен высокий поток гостей.',
    features: ['Вход: $2 600', 'Кеш-флоу: +$210/мес.', 'Срок: 8 мес.'],
    riskMeter: 3,
    liquidityMeter: 3,
    lockMonths: 8,
    effects: [
      { icon: '💰', text: '+$210/мес.' },
      { icon: '🧹', text: 'Оборот гостей' },
      { icon: '⚡', text: 'Риск падения спроса' },
    ],
    window: { minTurns: 2, maxTurns: 4, slots: 2 },
  },
  {
    id: 'mortgage_refi',
    title: 'Рефинансирование ипотеки',
    description: 'Снижаем ставку и получаем экономию по платежу.',
    icon: 'iconWallet',
    entryCost: 800,
    monthlyPayout: 120,
    durationMonths: 12,
    riskNote: 'Низкий риск — фиксированная ставка.',
    features: ['Вход: $800', 'Экономия: +$120/мес.', 'Срок: 12 мес.'],
    riskMeter: 1,
    liquidityMeter: 4,
    lockMonths: 12,
    effects: [
      { icon: '💰', text: '+$120/мес. экономии' },
      { icon: '🧾', text: 'Фикс. ставка' },
      { icon: '⚡', text: 'Разовый платёж' },
    ],
    window: { minTurns: 2, maxTurns: 5, slots: 3 },
  },
  {
    id: 'energy_retrofit',
    title: 'Энергоэффективный апгрейд',
    description: 'Замена окон и утепление, снижение коммуналки.',
    icon: 'iconBulb',
    entryCost: 1400,
    monthlyPayout: 95,
    durationMonths: 15,
    riskNote: 'Низкий риск — экономия предсказуема.',
    features: ['Вход: $1 400', 'Экономия: +$95/мес.', 'Срок: 15 мес.'],
    riskMeter: 1,
    liquidityMeter: 3,
    lockMonths: 15,
    effects: [
      { icon: '💡', text: 'Снижение коммуналки' },
      { icon: '💰', text: '+$95/мес.' },
      { icon: '⚡', text: 'Окупаемость 1+ года' },
    ],
    window: { minTurns: 3, maxTurns: 6, slots: 2 },
  },
  {
    id: 'condo_management',
    title: 'Управление апартаментами',
    description: 'Доля в компании, управляющей апарт-отелем.',
    icon: 'iconCard',
    entryCost: 5200,
    monthlyPayout: 260,
    durationMonths: 16,
    riskNote: 'Средний риск — зависит от турпотока.',
    features: ['Вход: $5 200', 'Дивиденд: +$260/мес.', 'Срок: 16 мес.'],
    riskMeter: 3,
    liquidityMeter: 2,
    lockMonths: 16,
    effects: [
      { icon: '💰', text: '+$260/мес.' },
      { icon: '🏨', text: 'Туристический спрос' },
      { icon: '⚡', text: 'Сезонные колебания' },
    ],
    window: { minTurns: 4, maxTurns: 7, slots: 1 },
  },
  {
    id: 'student_housing',
    title: 'Студенческое жильё',
    description: 'Сезонная аренда комнат возле кампуса.',
    icon: 'iconOwl',
    entryCost: 2400,
    monthlyPayout: 150,
    durationMonths: 10,
    riskNote: 'Средний риск — перерыв на летние месяцы.',
    features: ['Вход: $2 400', 'Аренда: +$150/мес.', 'Срок: 10 мес.'],
    riskMeter: 3,
    liquidityMeter: 3,
    lockMonths: 10,
    effects: [
      { icon: '💰', text: '+$150/мес.' },
      { icon: '🎓', text: 'Сезонность учебы' },
      { icon: '⚡', text: 'Перерывы летом' },
    ],
    window: { minTurns: 2, maxTurns: 5, slots: 2 },
  },
  {
    id: 'dental_membership',
    title: 'Стоматологический абонемент',
    description: 'Оплата за год с экономией на лечении.',
    icon: 'iconStethoscope',
    entryCost: 600,
    monthlyPayout: 60,
    durationMonths: 12,
    riskNote: 'Низкий риск — экономия гарантирована.',
    features: ['Вход: $600', 'Экономия: +$60/мес.', 'Срок: 12 мес.'],
    riskMeter: 1,
    liquidityMeter: 4,
    lockMonths: 12,
    effects: [
      { icon: '💰', text: '+$60/мес. экономии' },
      { icon: '🦷', text: 'Фикс. скидка' },
      { icon: '⚡', text: 'Годовой контракт' },
    ],
    window: { minTurns: 1, maxTurns: 3, slots: 3 },
  },
  {
    id: 'telemedicine_club',
    title: 'Клуб телемедицины',
    description: 'Пакет онлайн-консультаций с фиксированной ценой.',
    icon: 'iconStethoscope',
    entryCost: 450,
    monthlyPayout: 45,
    durationMonths: 10,
    riskNote: 'Низкий риск — экономия на визитах.',
    features: ['Вход: $450', 'Экономия: +$45/мес.', 'Срок: 10 мес.'],
    riskMeter: 1,
    liquidityMeter: 4,
    lockMonths: 10,
    effects: [
      { icon: '💰', text: '+$45/мес. экономии' },
      { icon: '📱', text: 'Онлайн-формат' },
      { icon: '⚡', text: 'Нужна подписка' },
    ],
    window: { minTurns: 1, maxTurns: 3, slots: 4 },
  },
  {
    id: 'lab_franchise',
    title: 'Франшиза лаборатории',
    description: 'Мини-доля в диагностическом пункте.',
    icon: 'iconStethoscope',
    entryCost: 4800,
    monthlyPayout: 260,
    durationMonths: 14,
    riskNote: 'Средний риск — зависит от потока пациентов.',
    features: ['Вход: $4 800', 'Дивиденд: +$260/мес.', 'Срок: 14 мес.'],
    riskMeter: 3,
    liquidityMeter: 2,
    lockMonths: 14,
    effects: [
      { icon: '💰', text: '+$260/мес.' },
      { icon: '🧪', text: 'Спрос на диагностику' },
      { icon: '⚡', text: 'Колебания потока' },
    ],
    window: { minTurns: 4, maxTurns: 7, slots: 1 },
  },
  {
    id: 'rehab_share',
    title: 'Доля в реабилитации',
    description: 'Часть дохода реабилитационного центра.',
    icon: 'iconCard',
    entryCost: 3000,
    monthlyPayout: 170,
    durationMonths: 12,
    riskNote: 'Средний риск — сезонность обращений.',
    features: ['Вход: $3 000', 'Дивиденд: +$170/мес.', 'Срок: 12 мес.'],
    riskMeter: 3,
    liquidityMeter: 2,
    lockMonths: 12,
    effects: [
      { icon: '💰', text: '+$170/мес.' },
      { icon: '🏥', text: 'Сезонные колебания' },
      { icon: '⚡', text: 'Паузы в выплатах' },
    ],
    window: { minTurns: 3, maxTurns: 6, slots: 2 },
  },
  {
    id: 'pharmacy_discount',
    title: 'Аптечный дисконт',
    description: 'Оптовый пакет лекарств со скидкой.',
    icon: 'iconCart',
    entryCost: 700,
    monthlyPayout: 70,
    durationMonths: 12,
    riskNote: 'Низкий риск — экономия на регулярных покупках.',
    features: ['Вход: $700', 'Экономия: +$70/мес.', 'Срок: 12 мес.'],
    riskMeter: 1,
    liquidityMeter: 4,
    lockMonths: 12,
    effects: [
      { icon: '💰', text: '+$70/мес. экономии' },
      { icon: '💊', text: 'Фикс. скидка' },
      { icon: '⚡', text: 'Пакет на год' },
    ],
    window: { minTurns: 1, maxTurns: 3, slots: 4 },
  },
  {
    id: 'vision_clinic',
    title: 'Пакет клиники зрения',
    description: 'Годовой пакет на коррекцию и диагностику.',
    icon: 'iconStethoscope',
    entryCost: 900,
    monthlyPayout: 75,
    durationMonths: 12,
    riskNote: 'Низкий риск — фиксированная экономия.',
    features: ['Вход: $900', 'Экономия: +$75/мес.', 'Срок: 12 мес.'],
    riskMeter: 1,
    liquidityMeter: 4,
    lockMonths: 12,
    effects: [
      { icon: '💰', text: '+$75/мес. экономии' },
      { icon: '👁️', text: 'Плановый сервис' },
      { icon: '⚡', text: 'Годовой контракт' },
    ],
    window: { minTurns: 2, maxTurns: 4, slots: 3 },
  },
  {
    id: 'fitness_corporate',
    title: 'Корпоративный фитнес',
    description: 'Групповой тариф снижает стоимость абонемента.',
    icon: 'iconSmile',
    entryCost: 500,
    monthlyPayout: 50,
    durationMonths: 10,
    riskNote: 'Низкий риск — фиксированная скидка.',
    features: ['Вход: $500', 'Экономия: +$50/мес.', 'Срок: 10 мес.'],
    riskMeter: 1,
    liquidityMeter: 5,
    lockMonths: 10,
    effects: [
      { icon: '💰', text: '+$50/мес. экономии' },
      { icon: '🏋️', text: 'Групповой тариф' },
      { icon: '⚡', text: 'Срок 10 мес.' },
    ],
    window: { minTurns: 1, maxTurns: 3, slots: 5 },
  },
  {
    id: 'medical_equipment_rental',
    title: 'Аренда медоборудования',
    description: 'Доход от аренды диагностического оборудования.',
    icon: 'iconCard',
    entryCost: 4100,
    monthlyPayout: 230,
    durationMonths: 12,
    riskNote: 'Средний риск — возможны простои.',
    features: ['Вход: $4 100', 'Аренда: +$230/мес.', 'Срок: 12 мес.'],
    riskMeter: 3,
    liquidityMeter: 2,
    lockMonths: 12,
    effects: [
      { icon: '💰', text: '+$230/мес.' },
      { icon: '⚙️', text: 'Нужен спрос клиник' },
      { icon: '⚡', text: 'Простои возможны' },
    ],
    window: { minTurns: 3, maxTurns: 6, slots: 2 },
  },
  {
    id: 'mental_health_app',
    title: 'Подписка на психологию',
    description: 'Годовой пакет с экономией на сессиях.',
    icon: 'iconSmile',
    entryCost: 650,
    monthlyPayout: 55,
    durationMonths: 12,
    riskNote: 'Низкий риск — экономия фиксирована.',
    features: ['Вход: $650', 'Экономия: +$55/мес.', 'Срок: 12 мес.'],
    riskMeter: 1,
    liquidityMeter: 4,
    lockMonths: 12,
    effects: [
      { icon: '💰', text: '+$55/мес. экономии' },
      { icon: '🧠', text: 'Пакет сессий' },
      { icon: '⚡', text: 'Годовая подписка' },
    ],
    window: { minTurns: 1, maxTurns: 3, slots: 4 },
  },
  {
    id: 'senior_care_share',
    title: 'Доля в центре ухода',
    description: 'Часть прибыли пансионата для пожилых.',
    icon: 'iconCard',
    entryCost: 5200,
    monthlyPayout: 280,
    durationMonths: 15,
    riskNote: 'Средний риск — зависит от загрузки.',
    features: ['Вход: $5 200', 'Дивиденд: +$280/мес.', 'Срок: 15 мес.'],
    riskMeter: 3,
    liquidityMeter: 2,
    lockMonths: 15,
    effects: [
      { icon: '💰', text: '+$280/мес.' },
      { icon: '🏥', text: 'Стабильный спрос' },
      { icon: '⚡', text: 'Колебания загрузки' },
    ],
    window: { minTurns: 4, maxTurns: 7, slots: 1 },
  },
  {
    id: 'taxi_lease',
    title: 'Лизинг такси',
    description: 'Покупка смены водителя на лизинговом авто.',
    icon: 'iconWallet',
    entryCost: 1700,
    monthlyPayout: 140,
    durationMonths: 8,
    riskNote: 'Средний риск — зависит от спроса.',
    features: ['Вход: $1 700', 'Кеш-флоу: +$140/мес.', 'Срок: 8 мес.'],
    riskMeter: 3,
    liquidityMeter: 3,
    lockMonths: 8,
    effects: [
      { icon: '💰', text: '+$140/мес.' },
      { icon: '🚕', text: 'Спрос на поездки' },
      { icon: '⚡', text: 'Риски простоя' },
    ],
    window: { minTurns: 2, maxTurns: 4, slots: 2 },
  },
  {
    id: 'cargo_van',
    title: 'Грузовой фургон',
    description: 'Доля в фургоне для локальных доставок.',
    icon: 'iconCart',
    entryCost: 3200,
    monthlyPayout: 210,
    durationMonths: 10,
    riskNote: 'Средний риск — зависит от заказов.',
    features: ['Вход: $3 200', 'Кеш-флоу: +$210/мес.', 'Срок: 10 мес.'],
    riskMeter: 3,
    liquidityMeter: 2,
    lockMonths: 10,
    effects: [
      { icon: '💰', text: '+$210/мес.' },
      { icon: '🚚', text: 'Локальные заказы' },
      { icon: '⚡', text: 'Простои возможны' },
    ],
    window: { minTurns: 3, maxTurns: 5, slots: 2 },
  },
  {
    id: 'scooter_fleet',
    title: 'Флот электросамокатов',
    description: 'Небольшая доля в городском парке самокатов.',
    icon: 'iconBulb',
    entryCost: 2800,
    monthlyPayout: 240,
    durationMonths: 7,
    riskNote: 'Высокий риск — износ и сезонность.',
    features: ['Вход: $2 800', 'Кеш-флоу: +$240/мес.', 'Срок: 7 мес.'],
    riskMeter: 5,
    liquidityMeter: 2,
    lockMonths: 7,
    effects: [
      { icon: '💰', text: '+$240/мес.' },
      { icon: '🛴', text: 'Сезонный спрос' },
      { icon: '⚡', text: 'Высокий износ' },
    ],
    window: { minTurns: 2, maxTurns: 4, slots: 1 },
  },
  {
    id: 'bike_share',
    title: 'Городской байк‑шеринг',
    description: 'Доля в сервисе проката велосипедов.',
    icon: 'iconPlant',
    entryCost: 2100,
    monthlyPayout: 150,
    durationMonths: 9,
    riskNote: 'Средний риск — зависит от погоды.',
    features: ['Вход: $2 100', 'Кеш-флоу: +$150/мес.', 'Срок: 9 мес.'],
    riskMeter: 3,
    liquidityMeter: 3,
    lockMonths: 9,
    effects: [
      { icon: '💰', text: '+$150/мес.' },
      { icon: '🚲', text: 'Погодные риски' },
      { icon: '⚡', text: 'Сезонность' },
    ],
    window: { minTurns: 2, maxTurns: 5, slots: 2 },
  },
  {
    id: 'ev_charger',
    title: 'Домашняя зарядка EV',
    description: 'Установка зарядки и сдача в аренду соседям.',
    icon: 'iconBulb',
    entryCost: 1500,
    monthlyPayout: 120,
    durationMonths: 11,
    riskNote: 'Низкий риск — стабильный спрос в районе.',
    features: ['Вход: $1 500', 'Кеш-флоу: +$120/мес.', 'Срок: 11 мес.'],
    riskMeter: 2,
    liquidityMeter: 3,
    lockMonths: 11,
    effects: [
      { icon: '💰', text: '+$120/мес.' },
      { icon: '🔌', text: 'Рост EV' },
      { icon: '⚡', text: 'Стабильный спрос' },
    ],
    window: { minTurns: 2, maxTurns: 4, slots: 3 },
  },
  {
    id: 'fuel_card',
    title: 'Топливная карта',
    description: 'Оптовая скидка на топливо.',
    icon: 'iconWallet',
    entryCost: 400,
    monthlyPayout: 45,
    durationMonths: 10,
    riskNote: 'Низкий риск — фиксированная скидка.',
    features: ['Вход: $400', 'Экономия: +$45/мес.', 'Срок: 10 мес.'],
    riskMeter: 1,
    liquidityMeter: 5,
    lockMonths: 10,
    effects: [
      { icon: '💰', text: '+$45/мес. экономии' },
      { icon: '⛽', text: 'Скидка на литр' },
      { icon: '⚡', text: 'Нужны регулярные поездки' },
    ],
    window: { minTurns: 1, maxTurns: 3, slots: 5 },
  },
  {
    id: 'fleet_maintenance',
    title: 'Пакет обслуживания авто',
    description: 'Предоплата ТО снижает средний чек.',
    icon: 'iconHardhat',
    entryCost: 600,
    monthlyPayout: 55,
    durationMonths: 12,
    riskNote: 'Низкий риск — экономия по договору.',
    features: ['Вход: $600', 'Экономия: +$55/мес.', 'Срок: 12 мес.'],
    riskMeter: 1,
    liquidityMeter: 4,
    lockMonths: 12,
    effects: [
      { icon: '💰', text: '+$55/мес. экономии' },
      { icon: '🛠️', text: 'Сервис включён' },
      { icon: '⚡', text: 'Годовой контракт' },
    ],
    window: { minTurns: 1, maxTurns: 4, slots: 4 },
  },
  {
    id: 'parking_pass',
    title: 'Городской паркинг‑пас',
    description: 'Абонемент на парковки с экономией.',
    icon: 'iconCard',
    entryCost: 500,
    monthlyPayout: 50,
    durationMonths: 12,
    riskNote: 'Низкий риск — фиксированная экономия.',
    features: ['Вход: $500', 'Экономия: +$50/мес.', 'Срок: 12 мес.'],
    riskMeter: 1,
    liquidityMeter: 5,
    lockMonths: 12,
    effects: [
      { icon: '💰', text: '+$50/мес. экономии' },
      { icon: '🅿️', text: 'Абонемент на год' },
      { icon: '⚡', text: 'Нужно парковаться регулярно' },
    ],
    window: { minTurns: 1, maxTurns: 3, slots: 5 },
  },
  {
    id: 'logistics_broker',
    title: 'Локальный логистический брокер',
    description: 'Комиссия за сведение грузов и перевозчиков.',
    icon: 'iconCoins',
    entryCost: 2200,
    monthlyPayout: 170,
    durationMonths: 9,
    riskNote: 'Средний риск — зависит от контрактов.',
    features: ['Вход: $2 200', 'Комиссия: +$170/мес.', 'Срок: 9 мес.'],
    riskMeter: 3,
    liquidityMeter: 3,
    lockMonths: 9,
    effects: [
      { icon: '💰', text: '+$170/мес.' },
      { icon: '📦', text: 'Контракты бизнеса' },
      { icon: '⚡', text: 'Срыв сделок возможен' },
    ],
    window: { minTurns: 2, maxTurns: 5, slots: 2 },
  },
  {
    id: 'ride_share_pool',
    title: 'Пул поездок',
    description: 'Доля в агрегаторе корпоративных поездок.',
    icon: 'iconWallet',
    entryCost: 2500,
    monthlyPayout: 180,
    durationMonths: 10,
    riskNote: 'Средний риск — зависит от корпоративных контрактов.',
    features: ['Вход: $2 500', 'Кеш-флоу: +$180/мес.', 'Срок: 10 мес.'],
    riskMeter: 3,
    liquidityMeter: 2,
    lockMonths: 10,
    effects: [
      { icon: '💰', text: '+$180/мес.' },
      { icon: '🚗', text: 'Контракты с компаниями' },
      { icon: '⚡', text: 'Срыв тендеров возможен' },
    ],
    window: { minTurns: 3, maxTurns: 6, slots: 2 },
  },
  {
    id: 'car_insurance_pool',
    title: 'Каско‑пул для автопарка',
    description: 'Групповой тариф снижает расходы на страховку.',
    icon: 'iconCard',
    entryCost: 650,
    monthlyPayout: 60,
    durationMonths: 12,
    riskNote: 'Низкий риск — фиксированная скидка.',
    features: ['Вход: $650', 'Экономия: +$60/мес.', 'Срок: 12 мес.'],
    riskMeter: 1,
    liquidityMeter: 4,
    lockMonths: 12,
    effects: [
      { icon: '💰', text: '+$60/мес. экономии' },
      { icon: '🛡️', text: 'Групповой тариф' },
      { icon: '⚡', text: 'Годовой договор' },
    ],
    window: { minTurns: 1, maxTurns: 3, slots: 4 },
  },
  {
    id: 'health_insurance_hmo',
    title: 'HMO‑страхование',
    description: 'План с фиксированной стоимостью услуг.',
    icon: 'iconStethoscope',
    entryCost: 900,
    monthlyPayout: 80,
    durationMonths: 12,
    riskNote: 'Низкий риск — экономия при регулярных визитах.',
    features: ['Вход: $900', 'Экономия: +$80/мес.', 'Срок: 12 мес.'],
    riskMeter: 1,
    liquidityMeter: 4,
    lockMonths: 12,
    effects: [
      { icon: '💰', text: '+$80/мес. экономии' },
      { icon: '🏥', text: 'Фикс. стоимость' },
      { icon: '⚡', text: 'Срок 12 мес.' },
    ],
    window: { minTurns: 2, maxTurns: 4, slots: 3 },
  },
  {
    id: 'property_insurance_reserve',
    title: 'Резерв по страхованию жилья',
    description: 'Скидка за предоплату полиса.',
    icon: 'iconWallet',
    entryCost: 500,
    monthlyPayout: 45,
    durationMonths: 12,
    riskNote: 'Низкий риск — экономия гарантирована.',
    features: ['Вход: $500', 'Экономия: +$45/мес.', 'Срок: 12 мес.'],
    riskMeter: 1,
    liquidityMeter: 5,
    lockMonths: 12,
    effects: [
      { icon: '💰', text: '+$45/мес. экономии' },
      { icon: '🏠', text: 'Предоплата полиса' },
      { icon: '⚡', text: 'Срок 12 мес.' },
    ],
    window: { minTurns: 1, maxTurns: 3, slots: 5 },
  },
  {
    id: 'liability_policy',
    title: 'Страхование ответственности',
    description: 'Полис снижает риски внезапных расходов.',
    icon: 'iconCard',
    entryCost: 700,
    monthlyPayout: 40,
    durationMonths: 12,
    riskNote: 'Низкий риск — защита бюджета.',
    features: ['Вход: $700', 'Защита: экв. +$40/мес.', 'Срок: 12 мес.'],
    riskMeter: 1,
    liquidityMeter: 4,
    lockMonths: 12,
    effects: [
      { icon: '🛡️', text: 'Защита расходов' },
      { icon: '💰', text: '+$40/мес. экв.' },
      { icon: '⚡', text: 'Годовой полис' },
    ],
    window: { minTurns: 1, maxTurns: 4, slots: 4 },
  },
  {
    id: 'travel_insurance',
    title: 'Туристическая страховка',
    description: 'Пакет на год с экономией на поездках.',
    icon: 'iconSmile',
    entryCost: 450,
    monthlyPayout: 35,
    durationMonths: 12,
    riskNote: 'Низкий риск — экономия на частых поездках.',
    features: ['Вход: $450', 'Экономия: +$35/мес.', 'Срок: 12 мес.'],
    riskMeter: 1,
    liquidityMeter: 5,
    lockMonths: 12,
    effects: [
      { icon: '💰', text: '+$35/мес. экономии' },
      { icon: '✈️', text: 'Пакет на год' },
      { icon: '⚡', text: 'Нужны поездки' },
    ],
    window: { minTurns: 1, maxTurns: 3, slots: 5 },
  },
  {
    id: 'device_insurance',
    title: 'Страхование гаджетов',
    description: 'Годовой план с фиксированной стоимостью ремонта.',
    icon: 'iconBulb',
    entryCost: 350,
    monthlyPayout: 30,
    durationMonths: 12,
    riskNote: 'Низкий риск — экономия на ремонтах.',
    features: ['Вход: $350', 'Экономия: +$30/мес.', 'Срок: 12 мес.'],
    riskMeter: 1,
    liquidityMeter: 5,
    lockMonths: 12,
    effects: [
      { icon: '💰', text: '+$30/мес. экономии' },
      { icon: '📱', text: 'Защита техники' },
      { icon: '⚡', text: 'Годовой план' },
    ],
    window: { minTurns: 1, maxTurns: 3, slots: 5 },
  },
  {
    id: 'pet_insurance',
    title: 'Страхование питомца',
    description: 'Фиксированные расходы на ветеринара.',
    icon: 'iconSmile',
    entryCost: 300,
    monthlyPayout: 30,
    durationMonths: 12,
    riskNote: 'Низкий риск — экономия при регулярных визитах.',
    features: ['Вход: $300', 'Экономия: +$30/мес.', 'Срок: 12 мес.'],
    riskMeter: 1,
    liquidityMeter: 5,
    lockMonths: 12,
    effects: [
      { icon: '💰', text: '+$30/мес. экономии' },
      { icon: '🐾', text: 'Фикс. тариф' },
      { icon: '⚡', text: 'Годовой полис' },
    ],
    window: { minTurns: 1, maxTurns: 3, slots: 5 },
  },
  {
    id: 'accident_policy',
    title: 'Полис от несчастных случаев',
    description: 'Компенсации снижают риск внезапных трат.',
    icon: 'iconCard',
    entryCost: 500,
    monthlyPayout: 35,
    durationMonths: 12,
    riskNote: 'Низкий риск — защита бюджета.',
    features: ['Вход: $500', 'Защита: экв. +$35/мес.', 'Срок: 12 мес.'],
    riskMeter: 1,
    liquidityMeter: 4,
    lockMonths: 12,
    effects: [
      { icon: '🛡️', text: 'Снижение рисков' },
      { icon: '💰', text: '+$35/мес. экв.' },
      { icon: '⚡', text: 'Годовой полис' },
    ],
    window: { minTurns: 1, maxTurns: 4, slots: 4 },
  },
  {
    id: 'crop_insurance',
    title: 'Страхование урожая',
    description: 'Покрытие рисков у фермеров.',
    icon: 'iconPlant',
    entryCost: 1200,
    monthlyPayout: 90,
    durationMonths: 12,
    riskNote: 'Средний риск — зависит от сезона.',
    features: ['Вход: $1 200', 'Премия: +$90/мес.', 'Срок: 12 мес.'],
    riskMeter: 3,
    liquidityMeter: 3,
    lockMonths: 12,
    effects: [
      { icon: '💰', text: '+$90/мес.' },
      { icon: '🌾', text: 'Сезонные риски' },
      { icon: '⚡', text: 'Погодные факторы' },
    ],
    window: { minTurns: 2, maxTurns: 5, slots: 2 },
  },
  {
    id: 'business_interruption',
    title: 'Страхование простоя бизнеса',
    description: 'Компенсации при форс‑мажорах.',
    icon: 'iconWallet',
    entryCost: 800,
    monthlyPayout: 50,
    durationMonths: 12,
    riskNote: 'Низкий риск — защита от убытков.',
    features: ['Вход: $800', 'Защита: экв. +$50/мес.', 'Срок: 12 мес.'],
    riskMeter: 1,
    liquidityMeter: 4,
    lockMonths: 12,
    effects: [
      { icon: '🛡️', text: 'Защита от простоя' },
      { icon: '💰', text: '+$50/мес. экв.' },
      { icon: '⚡', text: 'Годовой полис' },
    ],
    window: { minTurns: 1, maxTurns: 4, slots: 4 },
  },
  {
    id: 'streaming_bundle',
    title: 'Пакет стриминговых сервисов',
    description: 'Объединённая подписка дешевле.',
    icon: 'iconSmile',
    entryCost: 300,
    monthlyPayout: 25,
    durationMonths: 12,
    riskNote: 'Низкий риск — фиксированная экономия.',
    features: ['Вход: $300', 'Экономия: +$25/мес.', 'Срок: 12 мес.'],
    riskMeter: 1,
    liquidityMeter: 5,
    lockMonths: 12,
    effects: [
      { icon: '💰', text: '+$25/мес. экономии' },
      { icon: '🎬', text: 'Пакет сервисов' },
      { icon: '⚡', text: 'Годовая подписка' },
    ],
    window: { minTurns: 1, maxTurns: 2, slots: 6 },
  },
  {
    id: 'event_tickets',
    title: 'Выкуп билетов',
    description: 'Пакет билетов на события с перепродажей.',
    icon: 'iconGift',
    entryCost: 1300,
    monthlyPayout: 140,
    durationMonths: 6,
    riskNote: 'Высокий риск — зависит от спроса.',
    features: ['Вход: $1 300', 'Маржа: +$140/мес.', 'Срок: 6 мес.'],
    riskMeter: 5,
    liquidityMeter: 3,
    lockMonths: 6,
    effects: [
      { icon: '💰', text: '+$140/мес.' },
      { icon: '🎟️', text: 'Спрос на события' },
      { icon: '⚡', text: 'Риск непродажи' },
    ],
    window: { minTurns: 2, maxTurns: 4, slots: 1 },
  },
  {
    id: 'sports_season',
    title: 'Сезонные абонементы',
    description: 'Пакет абонементов с дробной перепродажей.',
    icon: 'iconSmile',
    entryCost: 1800,
    monthlyPayout: 160,
    durationMonths: 7,
    riskNote: 'Средний риск — зависит от команды.',
    features: ['Вход: $1 800', 'Маржа: +$160/мес.', 'Срок: 7 мес.'],
    riskMeter: 4,
    liquidityMeter: 3,
    lockMonths: 7,
    effects: [
      { icon: '💰', text: '+$160/мес.' },
      { icon: '🏟️', text: 'Спрос на игры' },
      { icon: '⚡', text: 'Риск падения интереса' },
    ],
    window: { minTurns: 2, maxTurns: 4, slots: 2 },
  },
  {
    id: 'cinema_ads',
    title: 'Реклама в кинотеатре',
    description: 'Микро‑доля в рекламных слотах.',
    icon: 'iconBulb',
    entryCost: 2200,
    monthlyPayout: 150,
    durationMonths: 10,
    riskNote: 'Средний риск — зависит от посещаемости.',
    features: ['Вход: $2 200', 'Доход: +$150/мес.', 'Срок: 10 мес.'],
    riskMeter: 3,
    liquidityMeter: 2,
    lockMonths: 10,
    effects: [
      { icon: '💰', text: '+$150/мес.' },
      { icon: '📺', text: 'Посещаемость важна' },
      { icon: '⚡', text: 'Сезонные спады' },
    ],
    window: { minTurns: 3, maxTurns: 6, slots: 2 },
  },
  {
    id: 'gaming_cafe',
    title: 'Кибер‑кафе',
    description: 'Доля в выручке игрового клуба.',
    icon: 'iconSmile',
    entryCost: 2600,
    monthlyPayout: 190,
    durationMonths: 9,
    riskNote: 'Средний риск — зависит от загрузки.',
    features: ['Вход: $2 600', 'Выручка: +$190/мес.', 'Срок: 9 мес.'],
    riskMeter: 3,
    liquidityMeter: 2,
    lockMonths: 9,
    effects: [
      { icon: '💰', text: '+$190/мес.' },
      { icon: '🎮', text: 'Зависит от потока' },
      { icon: '⚡', text: 'Сезонные пики' },
    ],
    window: { minTurns: 2, maxTurns: 5, slots: 2 },
  },
  {
    id: 'escape_room',
    title: 'Квест‑комнаты',
    description: 'Микро‑доля в сетке квестов.',
    icon: 'iconBulb',
    entryCost: 2100,
    monthlyPayout: 170,
    durationMonths: 8,
    riskNote: 'Средний риск — зависит от новизны.',
    features: ['Вход: $2 100', 'Выручка: +$170/мес.', 'Срок: 8 мес.'],
    riskMeter: 3,
    liquidityMeter: 3,
    lockMonths: 8,
    effects: [
      { icon: '💰', text: '+$170/мес.' },
      { icon: '🔒', text: 'Важна новизна' },
      { icon: '⚡', text: 'Риск падения интереса' },
    ],
    window: { minTurns: 2, maxTurns: 4, slots: 2 },
  },
  {
    id: 'festival_booth',
    title: 'Фуд‑стенд на фестивалях',
    description: 'Доля в прибыли сезонных фестивалей.',
    icon: 'iconCart',
    entryCost: 1900,
    monthlyPayout: 200,
    durationMonths: 6,
    riskNote: 'Высокий риск — зависит от погоды.',
    features: ['Вход: $1 900', 'Выручка: +$200/мес.', 'Срок: 6 мес.'],
    riskMeter: 5,
    liquidityMeter: 2,
    lockMonths: 6,
    effects: [
      { icon: '💰', text: '+$200/мес.' },
      { icon: '🌦️', text: 'Погодные риски' },
      { icon: '⚡', text: 'Сезонный формат' },
    ],
    window: { minTurns: 3, maxTurns: 5, slots: 1 },
  },
  {
    id: 'photo_booth',
    title: 'Мобильная фотобудка',
    description: 'Аренда фотобудки для мероприятий.',
    icon: 'iconGift',
    entryCost: 1600,
    monthlyPayout: 120,
    durationMonths: 9,
    riskNote: 'Средний риск — зависит от заказов.',
    features: ['Вход: $1 600', 'Аренда: +$120/мес.', 'Срок: 9 мес.'],
    riskMeter: 3,
    liquidityMeter: 3,
    lockMonths: 9,
    effects: [
      { icon: '💰', text: '+$120/мес.' },
      { icon: '📸', text: 'Зависит от событий' },
      { icon: '⚡', text: 'Сезонные спады' },
    ],
    window: { minTurns: 2, maxTurns: 5, slots: 2 },
  },
  {
    id: 'music_rights',
    title: 'Каталог музыкальных прав',
    description: 'Доля в роялти от каталога песен.',
    icon: 'iconCard',
    entryCost: 3600,
    monthlyPayout: 210,
    durationMonths: 14,
    riskNote: 'Средний риск — зависит от прослушиваний.',
    features: ['Вход: $3 600', 'Роялти: +$210/мес.', 'Срок: 14 мес.'],
    riskMeter: 3,
    liquidityMeter: 2,
    lockMonths: 14,
    effects: [
      { icon: '💰', text: '+$210/мес.' },
      { icon: '🎵', text: 'Зависит от стриминга' },
      { icon: '⚡', text: 'Тренды изменчивы' },
    ],
    window: { minTurns: 4, maxTurns: 7, slots: 1 },
  },
  {
    id: 'theater_subscription',
    title: 'Театральный абонемент',
    description: 'Годовой пакет со скидкой на спектакли.',
    icon: 'iconSmile',
    entryCost: 500,
    monthlyPayout: 40,
    durationMonths: 12,
    riskNote: 'Низкий риск — фиксированная экономия.',
    features: ['Вход: $500', 'Экономия: +$40/мес.', 'Срок: 12 мес.'],
    riskMeter: 1,
    liquidityMeter: 5,
    lockMonths: 12,
    effects: [
      { icon: '💰', text: '+$40/мес. экономии' },
      { icon: '🎭', text: 'Пакет на год' },
      { icon: '⚡', text: 'Нужны посещения' },
    ],
    window: { minTurns: 1, maxTurns: 3, slots: 5 },
  },
  {
    id: 'online_courses',
    title: 'Пакет онлайн‑курсов',
    description: 'Снижение затрат на обучение за счёт опта.',
    icon: 'iconOwl',
    entryCost: 600,
    monthlyPayout: 55,
    durationMonths: 12,
    riskNote: 'Низкий риск — экономия гарантирована.',
    features: ['Вход: $600', 'Экономия: +$55/мес.', 'Срок: 12 мес.'],
    riskMeter: 1,
    liquidityMeter: 4,
    lockMonths: 12,
    effects: [
      { icon: '💰', text: '+$55/мес. экономии' },
      { icon: '📚', text: 'Оптовая покупка' },
      { icon: '⚡', text: 'Годовой доступ' },
    ],
    window: { minTurns: 1, maxTurns: 3, slots: 4 },
  },
  {
    id: 'bootcamp_isa',
    title: 'Буткемп с ISA',
    description: 'Доля в доходе выпускников по договору ISA.',
    icon: 'iconGrowth',
    entryCost: 2400,
    monthlyPayout: 200,
    durationMonths: 9,
    riskNote: 'Высокий риск — зависит от трудоустройства.',
    features: ['Вход: $2 400', 'Доход: +$200/мес.', 'Срок: 9 мес.'],
    riskMeter: 5,
    liquidityMeter: 1,
    lockMonths: 9,
    effects: [
      { icon: '💰', text: '+$200/мес.' },
      { icon: '🎓', text: 'Риск невыплат' },
      { icon: '⚡', text: 'Зависит от рынка труда' },
    ],
    window: { minTurns: 3, maxTurns: 6, slots: 1 },
  },
  {
    id: 'tutoring_center',
    title: 'Центр репетиторства',
    description: 'Доля в выручке центра подготовки.',
    icon: 'iconOwl',
    entryCost: 2600,
    monthlyPayout: 170,
    durationMonths: 12,
    riskNote: 'Средний риск — сезонность экзаменов.',
    features: ['Вход: $2 600', 'Выручка: +$170/мес.', 'Срок: 12 мес.'],
    riskMeter: 3,
    liquidityMeter: 2,
    lockMonths: 12,
    effects: [
      { icon: '💰', text: '+$170/мес.' },
      { icon: '📝', text: 'Сезонность' },
      { icon: '⚡', text: 'Пик перед экзаменами' },
    ],
    window: { minTurns: 3, maxTurns: 6, slots: 2 },
  },
  {
    id: 'corporate_training',
    title: 'Корпоративные тренинги',
    description: 'Доля в контракте на обучение персонала.',
    icon: 'iconBulb',
    entryCost: 2800,
    monthlyPayout: 180,
    durationMonths: 9,
    riskNote: 'Средний риск — зависит от продления контракта.',
    features: ['Вход: $2 800', 'Выручка: +$180/мес.', 'Срок: 9 мес.'],
    riskMeter: 3,
    liquidityMeter: 3,
    lockMonths: 9,
    effects: [
      { icon: '💰', text: '+$180/мес.' },
      { icon: '🏢', text: 'Контрактные риски' },
      { icon: '⚡', text: 'Продление не гарантировано' },
    ],
    window: { minTurns: 3, maxTurns: 5, slots: 2 },
  },
  {
    id: 'language_school',
    title: 'Языковая школа',
    description: 'Доля в потоке новых групп.',
    icon: 'iconOwl',
    entryCost: 2300,
    monthlyPayout: 160,
    durationMonths: 11,
    riskNote: 'Средний риск — зависит от набора.',
    features: ['Вход: $2 300', 'Выручка: +$160/мес.', 'Срок: 11 мес.'],
    riskMeter: 3,
    liquidityMeter: 2,
    lockMonths: 11,
    effects: [
      { icon: '💰', text: '+$160/мес.' },
      { icon: '🗣️', text: 'Набор групп' },
      { icon: '⚡', text: 'Сезонные спады' },
    ],
    window: { minTurns: 2, maxTurns: 5, slots: 2 },
  },
  {
    id: 'certification_voucher',
    title: 'Ваучер на сертификацию',
    description: 'Оплата пакета экзаменов со скидкой.',
    icon: 'iconCalculator',
    entryCost: 700,
    monthlyPayout: 60,
    durationMonths: 12,
    riskNote: 'Низкий риск — фиксированная экономия.',
    features: ['Вход: $700', 'Экономия: +$60/мес.', 'Срок: 12 мес.'],
    riskMeter: 1,
    liquidityMeter: 4,
    lockMonths: 12,
    effects: [
      { icon: '💰', text: '+$60/мес. экономии' },
      { icon: '📄', text: 'Пакет экзаменов' },
      { icon: '⚡', text: 'Годовое использование' },
    ],
    window: { minTurns: 1, maxTurns: 3, slots: 4 },
  },
  {
    id: 'kids_coding',
    title: 'Детская школа программирования',
    description: 'Доля в выручке кружка.',
    icon: 'iconCalculator',
    entryCost: 2400,
    monthlyPayout: 165,
    durationMonths: 10,
    riskNote: 'Средний риск — зависит от набора.',
    features: ['Вход: $2 400', 'Выручка: +$165/мес.', 'Срок: 10 мес.'],
    riskMeter: 3,
    liquidityMeter: 2,
    lockMonths: 10,
    effects: [
      { icon: '💰', text: '+$165/мес.' },
      { icon: '💻', text: 'Набор групп' },
      { icon: '⚡', text: 'Сезонность' },
    ],
    window: { minTurns: 2, maxTurns: 5, slots: 2 },
  },
  {
    id: 'exam_prep',
    title: 'Подготовка к экзаменам',
    description: 'Доля в сезонных курсах подготовки.',
    icon: 'iconOwl',
    entryCost: 1900,
    monthlyPayout: 155,
    durationMonths: 8,
    riskNote: 'Средний риск — зависит от сезона.',
    features: ['Вход: $1 900', 'Выручка: +$155/мес.', 'Срок: 8 мес.'],
    riskMeter: 3,
    liquidityMeter: 3,
    lockMonths: 8,
    effects: [
      { icon: '💰', text: '+$155/мес.' },
      { icon: '🧠', text: 'Сезонный спрос' },
      { icon: '⚡', text: 'Снижение летом' },
    ],
    window: { minTurns: 2, maxTurns: 4, slots: 2 },
  },
  {
    id: 'e_learning_platform',
    title: 'Платформа e‑learning',
    description: 'Доля в подписках образовательной платформы.',
    icon: 'iconBulb',
    entryCost: 3400,
    monthlyPayout: 210,
    durationMonths: 12,
    riskNote: 'Средний риск — зависит от удержания.',
    features: ['Вход: $3 400', 'Подписки: +$210/мес.', 'Срок: 12 мес.'],
    riskMeter: 3,
    liquidityMeter: 2,
    lockMonths: 12,
    effects: [
      { icon: '💰', text: '+$210/мес.' },
      { icon: '📈', text: 'Удержание критично' },
      { icon: '⚡', text: 'Рост конкуренции' },
    ],
    window: { minTurns: 4, maxTurns: 7, slots: 1 },
  },
  {
    id: 'library_membership',
    title: 'Библиотечный абонемент',
    description: 'Годовой абонемент снижает расходы на книги.',
    icon: 'iconOwl',
    entryCost: 240,
    monthlyPayout: 20,
    durationMonths: 12,
    riskNote: 'Низкий риск — экономия фиксирована.',
    features: ['Вход: $240', 'Экономия: +$20/мес.', 'Срок: 12 мес.'],
    riskMeter: 1,
    liquidityMeter: 5,
    lockMonths: 12,
    effects: [
      { icon: '💰', text: '+$20/мес. экономии' },
      { icon: '📖', text: 'Годовой абонемент' },
      { icon: '⚡', text: 'Нужны чтения' },
    ],
    window: { minTurns: 1, maxTurns: 2, slots: 6 },
  },
  {
    id: 'coffee_kiosk',
    title: 'Кофейный киоск',
    description: 'Доля в точке формата to‑go.',
    icon: 'iconCart',
    entryCost: 2500,
    monthlyPayout: 180,
    durationMonths: 10,
    riskNote: 'Средний риск — зависит от локации.',
    features: ['Вход: $2 500', 'Выручка: +$180/мес.', 'Срок: 10 мес.'],
    riskMeter: 3,
    liquidityMeter: 2,
    lockMonths: 10,
    effects: [
      { icon: '💰', text: '+$180/мес.' },
      { icon: '☕', text: 'Трафик критичен' },
      { icon: '⚡', text: 'Сезонные колебания' },
    ],
    window: { minTurns: 2, maxTurns: 5, slots: 2 },
  },
  {
    id: 'vending_machine',
    title: 'Вендинговый автомат',
    description: 'Автомат в офисном центре.',
    icon: 'iconCart',
    entryCost: 1600,
    monthlyPayout: 120,
    durationMonths: 12,
    riskNote: 'Низкий риск — стабильный трафик.',
    features: ['Вход: $1 600', 'Выручка: +$120/мес.', 'Срок: 12 мес.'],
    riskMeter: 2,
    liquidityMeter: 3,
    lockMonths: 12,
    effects: [
      { icon: '💰', text: '+$120/мес.' },
      { icon: '🏢', text: 'Офисный трафик' },
      { icon: '⚡', text: 'Риск простоя' },
    ],
    window: { minTurns: 2, maxTurns: 4, slots: 3 },
  },
  {
    id: 'laundry_service',
    title: 'Прачечная самообслуживания',
    description: 'Доля в выручке прачечной.',
    icon: 'iconCard',
    entryCost: 3600,
    monthlyPayout: 220,
    durationMonths: 12,
    riskNote: 'Средний риск — зависит от трафика.',
    features: ['Вход: $3 600', 'Выручка: +$220/мес.', 'Срок: 12 мес.'],
    riskMeter: 3,
    liquidityMeter: 2,
    lockMonths: 12,
    effects: [
      { icon: '💰', text: '+$220/мес.' },
      { icon: '🧺', text: 'Стабильный спрос' },
      { icon: '⚡', text: 'Сезонные колебания' },
    ],
    window: { minTurns: 3, maxTurns: 6, slots: 2 },
  },
  {
    id: 'cleaning_contract',
    title: 'Клининговый контракт',
    description: 'Доля в обслуживании бизнес‑центра.',
    icon: 'iconHardhat',
    entryCost: 2200,
    monthlyPayout: 170,
    durationMonths: 9,
    riskNote: 'Низкий риск — контракт на год.',
    features: ['Вход: $2 200', 'Выручка: +$170/мес.', 'Срок: 9 мес.'],
    riskMeter: 2,
    liquidityMeter: 3,
    lockMonths: 9,
    effects: [
      { icon: '💰', text: '+$170/мес.' },
      { icon: '🧹', text: 'Контрактный доход' },
      { icon: '⚡', text: 'Риск разрыва невысок' },
    ],
    window: { minTurns: 2, maxTurns: 5, slots: 3 },
  },
  {
    id: 'coworking_desk',
    title: 'Рабочие места в коворкинге',
    description: 'Доля в абонементах резидентов.',
    icon: 'iconWallet',
    entryCost: 1800,
    monthlyPayout: 140,
    durationMonths: 11,
    riskNote: 'Средний риск — зависит от заполняемости.',
    features: ['Вход: $1 800', 'Выручка: +$140/мес.', 'Срок: 11 мес.'],
    riskMeter: 3,
    liquidityMeter: 3,
    lockMonths: 11,
    effects: [
      { icon: '💰', text: '+$140/мес.' },
      { icon: '🪑', text: 'Заполняемость важна' },
      { icon: '⚡', text: 'Сезонные спады' },
    ],
    window: { minTurns: 2, maxTurns: 5, slots: 2 },
  },
  {
    id: 'local_delivery',
    title: 'Локальная доставка',
    description: 'Доля в выручке районной доставки.',
    icon: 'iconCart',
    entryCost: 2000,
    monthlyPayout: 160,
    durationMonths: 10,
    riskNote: 'Средний риск — зависит от спроса.',
    features: ['Вход: $2 000', 'Выручка: +$160/мес.', 'Срок: 10 мес.'],
    riskMeter: 3,
    liquidityMeter: 3,
    lockMonths: 10,
    effects: [
      { icon: '💰', text: '+$160/мес.' },
      { icon: '📦', text: 'Спрос на доставку' },
      { icon: '⚡', text: 'Конкуренция растёт' },
    ],
    window: { minTurns: 2, maxTurns: 4, slots: 3 },
  },
  {
    id: 'b2b_leads',
    title: 'Пул B2B‑лидов',
    description: 'Доля в подписке на лид‑ген.',
    icon: 'iconBulb',
    entryCost: 1500,
    monthlyPayout: 130,
    durationMonths: 8,
    riskNote: 'Средний риск — зависит от конверсии.',
    features: ['Вход: $1 500', 'Комиссия: +$130/мес.', 'Срок: 8 мес.'],
    riskMeter: 3,
    liquidityMeter: 3,
    lockMonths: 8,
    effects: [
      { icon: '💰', text: '+$130/мес.' },
      { icon: '🎯', text: 'Конверсия лидов' },
      { icon: '⚡', text: 'Сезонные спады' },
    ],
    window: { minTurns: 2, maxTurns: 4, slots: 3 },
  },
  {
    id: 'marketing_retainer',
    title: 'Маркетинг‑ретейнер',
    description: 'Доля в контракте на обслуживание бренда.',
    icon: 'iconGrowth',
    entryCost: 2300,
    monthlyPayout: 175,
    durationMonths: 9,
    riskNote: 'Средний риск — зависит от продления.',
    features: ['Вход: $2 300', 'Выручка: +$175/мес.', 'Срок: 9 мес.'],
    riskMeter: 3,
    liquidityMeter: 2,
    lockMonths: 9,
    effects: [
      { icon: '💰', text: '+$175/мес.' },
      { icon: '📣', text: 'Контрактный доход' },
      { icon: '⚡', text: 'Продление не гарантировано' },
    ],
    window: { minTurns: 3, maxTurns: 5, slots: 2 },
  },
  {
    id: 'procurement_group',
    title: 'Группа закупок',
    description: 'Оптовые скидки на расходники для бизнеса.',
    icon: 'iconWallet',
    entryCost: 700,
    monthlyPayout: 70,
    durationMonths: 12,
    riskNote: 'Низкий риск — фиксированная экономия.',
    features: ['Вход: $700', 'Экономия: +$70/мес.', 'Срок: 12 мес.'],
    riskMeter: 1,
    liquidityMeter: 4,
    lockMonths: 12,
    effects: [
      { icon: '💰', text: '+$70/мес. экономии' },
      { icon: '🧾', text: 'Оптовые цены' },
      { icon: '⚡', text: 'Годовой договор' },
    ],
    window: { minTurns: 1, maxTurns: 3, slots: 4 },
  },
  {
    id: 'maintenance_contract',
    title: 'Договор на обслуживание',
    description: 'Доля в контракте на техобслуживание зданий.',
    icon: 'iconHardhat',
    entryCost: 2600,
    monthlyPayout: 190,
    durationMonths: 10,
    riskNote: 'Низкий риск — фиксированный контракт.',
    features: ['Вход: $2 600', 'Выручка: +$190/мес.', 'Срок: 10 мес.'],
    riskMeter: 2,
    liquidityMeter: 2,
    lockMonths: 10,
    effects: [
      { icon: '💰', text: '+$190/мес.' },
      { icon: '🛠️', text: 'Контракт на год' },
      { icon: '⚡', text: 'Риск разрыва низкий' },
    ],
    window: { minTurns: 2, maxTurns: 5, slots: 2 },
  },
  {
    id: 'municipal_bond_pool',
    title: 'Пул муниципальных облигаций',
    description: 'Консервативный доход от облигаций.',
    icon: 'iconCoins',
    entryCost: 3000,
    monthlyPayout: 140,
    durationMonths: 18,
    riskNote: 'Низкий риск — доход умеренный.',
    features: ['Вход: $3 000', 'Купон: +$140/мес.', 'Срок: 18 мес.'],
    riskMeter: 1,
    liquidityMeter: 2,
    lockMonths: 18,
    effects: [
      { icon: '💰', text: '+$140/мес.' },
      { icon: '🏛️', text: 'Консервативный доход' },
      { icon: '⚡', text: 'Долгий срок' },
    ],
    window: { minTurns: 4, maxTurns: 7, slots: 2 },
  },
  {
    id: 'dividend_note',
    title: 'Дивидендная нота',
    description: 'Фиксированный купон с привязкой к индексу.',
    icon: 'iconGrowth',
    entryCost: 2800,
    monthlyPayout: 160,
    durationMonths: 12,
    riskNote: 'Средний риск — возможна просадка индекса.',
    features: ['Вход: $2 800', 'Купон: +$160/мес.', 'Срок: 12 мес.'],
    riskMeter: 3,
    liquidityMeter: 2,
    lockMonths: 12,
    effects: [
      { icon: '💰', text: '+$160/мес.' },
      { icon: '📈', text: 'Привязка к индексу' },
      { icon: '⚡', text: 'Риск снижения' },
    ],
    window: { minTurns: 3, maxTurns: 6, slots: 2 },
  },
  {
    id: 'gold_storage',
    title: 'Золото на хранении',
    description: 'Доход от аренды ячеек и комиссий.',
    icon: 'iconCoins',
    entryCost: 3200,
    monthlyPayout: 150,
    durationMonths: 14,
    riskNote: 'Низкий риск — стабильный спрос.',
    features: ['Вход: $3 200', 'Комиссия: +$150/мес.', 'Срок: 14 мес.'],
    riskMeter: 2,
    liquidityMeter: 2,
    lockMonths: 14,
    effects: [
      { icon: '💰', text: '+$150/мес.' },
      { icon: '🥇', text: 'Стабильный спрос' },
      { icon: '⚡', text: 'Капитал заморожен' },
    ],
    window: { minTurns: 3, maxTurns: 6, slots: 2 },
  },
  {
    id: 'p2p_loans',
    title: 'P2P‑займы',
    description: 'Портфель микрозаймов с повышенной доходностью.',
    icon: 'iconWallet',
    entryCost: 2200,
    monthlyPayout: 190,
    durationMonths: 8,
    riskNote: 'Высокий риск — возможны дефолты.',
    features: ['Вход: $2 200', 'Проценты: +$190/мес.', 'Срок: 8 мес.'],
    riskMeter: 5,
    liquidityMeter: 2,
    lockMonths: 8,
    effects: [
      { icon: '💰', text: '+$190/мес.' },
      { icon: '⚡', text: 'Риск дефолтов' },
      { icon: '📉', text: 'Просадка портфеля' },
    ],
    window: { minTurns: 2, maxTurns: 4, slots: 1 },
  },
  {
    id: 'structured_note',
    title: 'Структурная нота',
    description: 'Доход при умеренной волатильности.',
    icon: 'iconGrowth',
    entryCost: 3500,
    monthlyPayout: 190,
    durationMonths: 12,
    riskNote: 'Средний риск — барьерные условия.',
    features: ['Вход: $3 500', 'Купон: +$190/мес.', 'Срок: 12 мес.'],
    riskMeter: 4,
    liquidityMeter: 1,
    lockMonths: 12,
    effects: [
      { icon: '💰', text: '+$190/мес.' },
      { icon: '📈', text: 'Барьерные условия' },
      { icon: '⚡', text: 'Риск досрочного снижения' },
    ],
    window: { minTurns: 4, maxTurns: 7, slots: 1 },
  },
  {
    id: 'invoice_factoring',
    title: 'Факторинг счетов',
    description: 'Выкуп дебиторки с дисконтом.',
    icon: 'iconCard',
    entryCost: 2600,
    monthlyPayout: 170,
    durationMonths: 7,
    riskNote: 'Средний риск — задержки оплат.',
    features: ['Вход: $2 600', 'Маржа: +$170/мес.', 'Срок: 7 мес.'],
    riskMeter: 3,
    liquidityMeter: 3,
    lockMonths: 7,
    effects: [
      { icon: '💰', text: '+$170/мес.' },
      { icon: '🧾', text: 'Риск задержек' },
      { icon: '⚡', text: 'Нужен контроль дебиторки' },
    ],
    window: { minTurns: 2, maxTurns: 5, slots: 2 },
  },
  {
    id: 'equipment_leasing',
    title: 'Лизинг оборудования',
    description: 'Аренда оборудования малому бизнесу.',
    icon: 'iconHardhat',
    entryCost: 3400,
    monthlyPayout: 200,
    durationMonths: 12,
    riskNote: 'Средний риск — зависит от платежей.',
    features: ['Вход: $3 400', 'Лизинг: +$200/мес.', 'Срок: 12 мес.'],
    riskMeter: 3,
    liquidityMeter: 2,
    lockMonths: 12,
    effects: [
      { icon: '💰', text: '+$200/мес.' },
      { icon: '⚙️', text: 'Спрос на аренду' },
      { icon: '⚡', text: 'Риск просрочек' },
    ],
    window: { minTurns: 3, maxTurns: 6, slots: 2 },
  },
  {
    id: 'franchise_buyback',
    title: 'Франшиза с buy‑back',
    description: 'Вход в франшизу с опцией выкупа.',
    icon: 'iconCart',
    entryCost: 5200,
    monthlyPayout: 260,
    durationMonths: 16,
    riskNote: 'Средний риск — зависит от продаж.',
    features: ['Вход: $5 200', 'Роялти: +$260/мес.', 'Срок: 16 мес.'],
    riskMeter: 3,
    liquidityMeter: 1,
    lockMonths: 16,
    effects: [
      { icon: '💰', text: '+$260/мес.' },
      { icon: '🏪', text: 'Франшизные продажи' },
      { icon: '⚡', text: 'Долгая заморозка' },
    ],
    window: { minTurns: 4, maxTurns: 8, slots: 1 },
  },
  {
    id: 'retail_inventory',
    title: 'Партия розничного товара',
    description: 'Оптовая закупка с перепродажей.',
    icon: 'iconCart',
    entryCost: 1800,
    monthlyPayout: 150,
    durationMonths: 6,
    riskNote: 'Средний риск — зависит от спроса.',
    features: ['Вход: $1 800', 'Маржа: +$150/мес.', 'Срок: 6 мес.'],
    riskMeter: 4,
    liquidityMeter: 3,
    lockMonths: 6,
    effects: [
      { icon: '💰', text: '+$150/мес.' },
      { icon: '🛒', text: 'Спрос на товар' },
      { icon: '⚡', text: 'Риск неликвида' },
    ],
    window: { minTurns: 2, maxTurns: 4, slots: 2 },
  },
  {
    id: 'import_batch',
    title: 'Импортная партия',
    description: 'Поставка товара с валютным риском.',
    icon: 'iconGrowth',
    entryCost: 4200,
    monthlyPayout: 260,
    durationMonths: 8,
    riskNote: 'Высокий риск — курс и логистика.',
    features: ['Вход: $4 200', 'Маржа: +$260/мес.', 'Срок: 8 мес.'],
    riskMeter: 5,
    liquidityMeter: 1,
    lockMonths: 8,
    effects: [
      { icon: '💰', text: '+$260/мес.' },
      { icon: '🚢', text: 'Риски логистики' },
      { icon: '⚡', text: 'Колебания курса' },
    ],
    window: { minTurns: 4, maxTurns: 7, slots: 1 },
  },
  {
    id: 'ai_saas_seed',
    title: 'AI SaaS pre‑seed',
    description: 'Доля в подписках стартапа.',
    icon: 'iconGrowth',
    entryCost: 3000,
    monthlyPayout: 220,
    durationMonths: 10,
    riskNote: 'Высокий риск — продукт ещё ищет рынок.',
    features: ['Вход: $3 000', 'MRR: +$220/мес.', 'Срок: 10 мес.'],
    riskMeter: 5,
    liquidityMeter: 1,
    lockMonths: 10,
    effects: [
      { icon: '💰', text: '+$220/мес.' },
      { icon: '🤖', text: 'Риск PMF' },
      { icon: '⚡', text: 'Волатильный рост' },
    ],
    window: { minTurns: 4, maxTurns: 7, slots: 1 },
  },
  {
    id: 'app_revenue_share',
    title: 'Revenue‑share приложения',
    description: 'Доля в рекламной выручке приложения.',
    icon: 'iconBulb',
    entryCost: 1800,
    monthlyPayout: 150,
    durationMonths: 8,
    riskNote: 'Средний риск — зависит от трафика.',
    features: ['Вход: $1 800', 'Выручка: +$150/мес.', 'Срок: 8 мес.'],
    riskMeter: 4,
    liquidityMeter: 2,
    lockMonths: 8,
    effects: [
      { icon: '💰', text: '+$150/мес.' },
      { icon: '📱', text: 'Трафик важен' },
      { icon: '⚡', text: 'Риск падения MAU' },
    ],
    window: { minTurns: 3, maxTurns: 6, slots: 2 },
  },
  {
    id: 'marketplace_equity',
    title: 'Доля в маркетплейсе',
    description: 'Комиссии от продаж продавцов.',
    icon: 'iconCart',
    entryCost: 3400,
    monthlyPayout: 210,
    durationMonths: 12,
    riskNote: 'Средний риск — зависит от продавцов.',
    features: ['Вход: $3 400', 'Комиссия: +$210/мес.', 'Срок: 12 мес.'],
    riskMeter: 4,
    liquidityMeter: 1,
    lockMonths: 12,
    effects: [
      { icon: '💰', text: '+$210/мес.' },
      { icon: '🛍️', text: 'Сеть продавцов' },
      { icon: '⚡', text: 'Конкуренция растёт' },
    ],
    window: { minTurns: 4, maxTurns: 7, slots: 1 },
  },
  {
    id: 'hardware_preorder',
    title: 'Предзаказ гаджетов',
    description: 'Маржа на партии устройств с предоплатой.',
    icon: 'iconBulb',
    entryCost: 2600,
    monthlyPayout: 190,
    durationMonths: 7,
    riskNote: 'Высокий риск — срывы поставки.',
    features: ['Вход: $2 600', 'Маржа: +$190/мес.', 'Срок: 7 мес.'],
    riskMeter: 5,
    liquidityMeter: 1,
    lockMonths: 7,
    effects: [
      { icon: '💰', text: '+$190/мес.' },
      { icon: '📦', text: 'Риск задержек' },
      { icon: '⚡', text: 'Неустойчивый спрос' },
    ],
    window: { minTurns: 3, maxTurns: 5, slots: 1 },
  },
  {
    id: 'biotech_seed',
    title: 'Biotech seed',
    description: 'Доля в ранних исследованиях.',
    icon: 'iconStethoscope',
    entryCost: 4000,
    monthlyPayout: 240,
    durationMonths: 14,
    riskNote: 'Высокий риск — научная неопределённость.',
    features: ['Вход: $4 000', 'Потенциал: +$240/мес.', 'Срок: 14 мес.'],
    riskMeter: 5,
    liquidityMeter: 1,
    lockMonths: 14,
    effects: [
      { icon: '💰', text: '+$240/мес.' },
      { icon: '🧬', text: 'Научный риск' },
      { icon: '⚡', text: 'Долгая заморозка' },
    ],
    window: { minTurns: 5, maxTurns: 8, slots: 1 },
  },
  {
    id: 'fintech_microloan',
    title: 'Fintech микрозаймы',
    description: 'Доля в портфеле МФО‑платформы.',
    icon: 'iconWallet',
    entryCost: 2400,
    monthlyPayout: 200,
    durationMonths: 8,
    riskNote: 'Высокий риск — дефолты клиентов.',
    features: ['Вход: $2 400', 'Проценты: +$200/мес.', 'Срок: 8 мес.'],
    riskMeter: 5,
    liquidityMeter: 2,
    lockMonths: 8,
    effects: [
      { icon: '💰', text: '+$200/мес.' },
      { icon: '⚡', text: 'Риск дефолтов' },
      { icon: '📉', text: 'Волатильность' },
    ],
    window: { minTurns: 3, maxTurns: 6, slots: 1 },
  },
  {
    id: 'gaming_studio',
    title: 'Игровая студия',
    description: 'Доля в будущих релизах.',
    icon: 'iconSmile',
    entryCost: 2800,
    monthlyPayout: 190,
    durationMonths: 10,
    riskNote: 'Высокий риск — зависит от релиза.',
    features: ['Вход: $2 800', 'Роялти: +$190/мес.', 'Срок: 10 мес.'],
    riskMeter: 5,
    liquidityMeter: 1,
    lockMonths: 10,
    effects: [
      { icon: '💰', text: '+$190/мес.' },
      { icon: '🎮', text: 'Риск провала релиза' },
      { icon: '⚡', text: 'Долгая разработка' },
    ],
    window: { minTurns: 4, maxTurns: 7, slots: 1 },
  },
  {
    id: 'cybersec_tool',
    title: 'Инструмент кибер‑безопасности',
    description: 'Доля в подписках B2B‑продукта.',
    icon: 'iconBulb',
    entryCost: 3000,
    monthlyPayout: 200,
    durationMonths: 11,
    riskNote: 'Средний риск — зависит от продаж.',
    features: ['Вход: $3 000', 'MRR: +$200/мес.', 'Срок: 11 мес.'],
    riskMeter: 4,
    liquidityMeter: 1,
    lockMonths: 11,
    effects: [
      { icon: '💰', text: '+$200/мес.' },
      { icon: '🔐', text: 'Зависит от B2B продаж' },
      { icon: '⚡', text: 'Длинный цикл сделки' },
    ],
    window: { minTurns: 4, maxTurns: 7, slots: 1 },
  },
  {
    id: 'climate_tech',
    title: 'Climate‑tech пилот',
    description: 'Доля в пилоте по снижению выбросов.',
    icon: 'iconPlant',
    entryCost: 2600,
    monthlyPayout: 170,
    durationMonths: 12,
    riskNote: 'Высокий риск — зависит от регулятора.',
    features: ['Вход: $2 600', 'Гранты: +$170/мес.', 'Срок: 12 мес.'],
    riskMeter: 5,
    liquidityMeter: 1,
    lockMonths: 12,
    effects: [
      { icon: '💰', text: '+$170/мес.' },
      { icon: '🌍', text: 'Регуляторные риски' },
      { icon: '⚡', text: 'Пилот может закрыться' },
    ],
    window: { minTurns: 5, maxTurns: 8, slots: 1 },
  },
  {
    id: 'foodtech',
    title: 'Food‑tech кухня',
    description: 'Доля в облачной кухне.',
    icon: 'iconCart',
    entryCost: 2200,
    monthlyPayout: 165,
    durationMonths: 9,
    riskNote: 'Средний риск — зависит от заказов.',
    features: ['Вход: $2 200', 'Выручка: +$165/мес.', 'Срок: 9 мес.'],
    riskMeter: 4,
    liquidityMeter: 2,
    lockMonths: 9,
    effects: [
      { icon: '💰', text: '+$165/мес.' },
      { icon: '🍲', text: 'Зависит от заказов' },
      { icon: '⚡', text: 'Риск конкуренции' },
    ],
    window: { minTurns: 3, maxTurns: 6, slots: 2 },
  },
  {
    id: 'agriculture_greenhouse',
    title: 'Тепличное хозяйство',
    description: 'Доля в выручке круглогодичных теплиц.',
    icon: 'iconPlant',
    entryCost: 2800,
    monthlyPayout: 180,
    durationMonths: 12,
    riskNote: 'Средний риск — зависит от урожайности.',
    features: ['Вход: $2 800', 'Выручка: +$180/мес.', 'Срок: 12 мес.'],
    riskMeter: 3,
    liquidityMeter: 2,
    lockMonths: 12,
    effects: [
      { icon: '💰', text: '+$180/мес.' },
      { icon: '🌿', text: 'Урожайные риски' },
      { icon: '⚡', text: 'Сезонные колебания' },
    ],
    window: { minTurns: 3, maxTurns: 6, slots: 2 },
  },
  {
    id: 'renewable_microgrid',
    title: 'Микрогенерация энергии',
    description: 'Доля в локальной солнечной станции.',
    icon: 'iconBulb',
    entryCost: 4200,
    monthlyPayout: 230,
    durationMonths: 18,
    riskNote: 'Низкий риск — долгий контракт выкупа.',
    features: ['Вход: $4 200', 'Выкуп: +$230/мес.', 'Срок: 18 мес.'],
    riskMeter: 2,
    liquidityMeter: 1,
    lockMonths: 18,
    effects: [
      { icon: '💰', text: '+$230/мес.' },
      { icon: '☀️', text: 'Долгий контракт' },
      { icon: '⚡', text: 'Долгая заморозка' },
    ],
    window: { minTurns: 5, maxTurns: 9, slots: 1 },
  },
  {
    id: 'water_purification',
    title: 'Очистка воды',
    description: 'Доля в обслуживании системы фильтрации.',
    icon: 'iconBulb',
    entryCost: 2400,
    monthlyPayout: 160,
    durationMonths: 13,
    riskNote: 'Низкий риск — долгосрочный контракт.',
    features: ['Вход: $2 400', 'Выручка: +$160/мес.', 'Срок: 13 мес.'],
    riskMeter: 2,
    liquidityMeter: 2,
    lockMonths: 13,
    effects: [
      { icon: '💰', text: '+$160/мес.' },
      { icon: '🚰', text: 'Контракт на сервис' },
      { icon: '⚡', text: 'Риск разрыва низкий' },
    ],
    window: { minTurns: 3, maxTurns: 6, slots: 2 },
  },
  {
    id: 'wedding_service',
    title: 'Сервис для свадеб',
    description: 'Доля в бронированиях банкетов.',
    icon: 'iconGift',
    entryCost: 1800,
    monthlyPayout: 150,
    durationMonths: 7,
    riskNote: 'Средний риск — сезонность.',
    features: ['Вход: $1 800', 'Выручка: +$150/мес.', 'Срок: 7 мес.'],
    riskMeter: 3,
    liquidityMeter: 3,
    lockMonths: 7,
    effects: [
      { icon: '💰', text: '+$150/мес.' },
      { icon: '💍', text: 'Сезонные пики' },
      { icon: '⚡', text: 'Риск отмен' },
    ],
    window: { minTurns: 2, maxTurns: 4, slots: 2 },
  },
  {
    id: 'recycling_contract',
    title: 'Контракт на переработку',
    description: 'Доля в выручке переработки вторсырья.',
    icon: 'iconPlant',
    entryCost: 2600,
    monthlyPayout: 170,
    durationMonths: 12,
    riskNote: 'Средний риск — зависит от цен на сырьё.',
    features: ['Вход: $2 600', 'Выручка: +$170/мес.', 'Срок: 12 мес.'],
    riskMeter: 3,
    liquidityMeter: 2,
    lockMonths: 12,
    effects: [
      { icon: '💰', text: '+$170/мес.' },
      { icon: '♻️', text: 'Цены на сырьё' },
      { icon: '⚡', text: 'Колебания маржи' },
    ],
    window: { minTurns: 3, maxTurns: 6, slots: 2 },
  },
  {
    id: 'data_center_rack',
    title: 'Стойка в дата‑центре',
    description: 'Доля в аренде серверной стойки.',
    icon: 'iconBulb',
    entryCost: 3800,
    monthlyPayout: 210,
    durationMonths: 14,
    riskNote: 'Средний риск — зависит от заполнения.',
    features: ['Вход: $3 800', 'Аренда: +$210/мес.', 'Срок: 14 мес.'],
    riskMeter: 3,
    liquidityMeter: 2,
    lockMonths: 14,
    effects: [
      { icon: '💰', text: '+$210/мес.' },
      { icon: '🖥️', text: 'Заполнение стойки' },
      { icon: '⚡', text: 'Риски оттока' },
    ],
    window: { minTurns: 4, maxTurns: 7, slots: 1 },
  },
];

export const DEAL_TEMPLATES = RAW_DEAL_TEMPLATES.map((deal) =>
  TERM_DEAL_IDS.has(deal.id)
    ? deal
    : {
        ...deal,
        durationMonths: null,
        lockMonths: null,
      },
);

export const DEAL_WINDOW_RULES = DEAL_TEMPLATES.reduce((acc, deal) => {
  acc[deal.id] = {
    minTurns: deal.window?.minTurns ?? 2,
    maxTurns: deal.window?.maxTurns ?? deal.window?.minTurns ?? 2,
    slots: deal.window?.slots ?? 1,
  };
  return acc;
}, {});

export function getDealTemplateById(id) {
  return DEAL_TEMPLATES.find((deal) => deal.id === id);
}
